version: '2'

services:
  mass-labeling:
    container_name: mass-labeling
    build: .
    env_file:
    - ./config/app.env
    environment:
      NODE_ENV: production
      DB_URL: mongodb://mongo:27017/mass-labeling
      PORT: 80
    volumes:
    - ./config/app.yml:/usr/bin/app/config/app.yml
    - ./data:/usr/bin/app/data
    ports:
    - __PORT__:80
    depends_on:
    - mongo
    restart: always

  mongo:
    container_name: mass-labeling-mongo
    image: mongo:3.6
    volumes:
    - ./data/mongo:/data/db
    restart: always
